Team-EverFlow/Koreasy-Dev

.gitignore
package-lock.json
package.json
src/firebase/api/authAPI.js
src/firebase/functions/util.js
src/firebase/root.js
src/firebase/type/const.js
src/firebase/type/typedef.js

[Feat] #17 - 구글 로그인 구현

---

src/firebase/api/authAPI.js

- closes #22
- GoogleAuth  함수의 jsdoc 설명 부분이 수정되었습니다. data -> user

[Fix] #22 - Update GoogleAuth jsdoc

---

src/firebase/api/userAPI.js
src/firebase/type/const.js

- closes #21
- 유저 정보를 DB에 저장하기
- 유저 정보를 DB에서 불러오기 (UID를 이용하여)
- Firebase에서 제공하는 유저 정보 불러오기

[Feat] #21 - Add Set user and Get user

---

src/components/Chevrion.jsx
src/components/Header.jsx
src/components/NavigationBar.jsx
src/components/PageTitle.jsx

- closes #32
- `<Header/>`에 `<Footer/>` 삭제했습니다.
- `<Header/>`에 isNavigationBar, isPageTitle, viewName, navigationViewName parameter 추가하였습니다. (사용 방법은 jsdoc를 확인해주세요.)
- `<NavigationBar/>`에 viewName parameter 추가하였습니다.
- `<PageTitle/>`에 viewName parameter 추가하였습니다.
|iPhone 12 Pro|Samsung Galaxy S20 Ultra|
|:---:|:---:|
|![localhost_3000_(iPhone 12 Pro) (1)](https://github.com/Team-EverFlow/Koreasy/assets/16767890/d032972c-ba61-4c31-8986-9ad56eeb5b4c)|![localhost_3000_(Samsung Galaxy S20 Ultra) (1)](https://github.com/Team-EverFlow/Koreasy/assets/16767890/dac6921c-3f51-4415-a1ac-40af933c68db)|

[Bugfix] Can't send argument to central component

---

src/firebase/api/userAPI.js
src/firebase/api/wordAPI.js

- closes #38 
- 특정 단어를 현재 유저 프로필 정보의 북마크 목록에 추가 / 제거
- 유저가 처음 가입했을때 초기화 값 수정

[Feat] bookmark add remove

---

src/firebase/api/userAPI.js

- closes #51 
- 회원가입 함수를 수정하였습니다. (추가적인 데이터 전달이 없을 경우 현재 유저의 데이터를 자동으로 입력해줍니다)

[Feat] - #51 register function

---

src/firebase/api/QuizApi.js
src/firebase/type/const.js
src/firebase/type/typedef.js

- closes #60 
- WordTestView 와 관련된 데이터 타입과 함수를 추가했습니다. 
- 각 타입에 대한 설명은 notion 페이지에 공유드리겠습니다.
- GetWordTestList -> DB에 저장된 WordTest를 List로 반환합니다.
- GetTestDataList -> id값을 이용하여 DB에 저장된 TestData를 불러옵니다

[Feat] - #60 Add GetWordTestList and GetTestDataList

---

src/firebase/api/wordAPI.js
src/firebase/type/const.js
src/firebase/type/typedef.js

- closes #74
- 댓글 타입 추가
- CreateComment 추가
- DeleteComment 추가

[Feat] - #74 Add comment function

---

src/firebase/api/QuizApi.js
src/firebase/api/userAPI.js
src/firebase/type/typedef.js

- closes #78 
- 모의고사 점수를 저장하는 기능을 구현했습니다
- UserInformation 타입에 testScore[]를 추가했습니다.
- SetTestScore 현재 유저의 UserInformation에 testScore를 추가합니다.

[Feat] - #78 Add testscore

---

src/firebase/api/authAPI.js

- closes #86
- 파이어베이스 로그인 정보를 로컬에 저장하여 인증 상태 유지하도록 수정했습니다.

[Feat] - #86 Add login-state-persistence

---

src/firebase/api/BadgeApi.js

- closes #82
- 사용자의 대표 뱃지 목록에 뱃지id를 추가하는 함수를 구현했습니다.

[Feat] - #82 Add AddRepBadge

---

src/firebase/api/authAPI.js
src/firebase/root.js

- closes #91 
-  setPersistance 함수의 위치를 변경했습니다.

[Fix] - #91 Fix login persistence

---

src/firebase/api/wordAPI.js
src/firebase/type/typedef.js

- closes #83 
- Date 값을 Timestamp 값으로 변경했습니다.
- date에 저장할때 Date 타입이 아닌 Timestamp로 저장하도록 변경했습니다.

[Feat] - 83 date type return

---

src/firebase/api/userAPI.js

- closes #93 
- 현재 유저가 로그아웃 상태일 경우 에러를 리턴합니다.

[Fix] - #93 Modify GetCurrentUserInformation function

---

src/firebase/api/userAPI.js

- closes #96 
- 로그아웃 함수를 작성했습니다

[Feat] logout

---

src/firebase/api/wordAPI.js

- closes #97 
- 오늘의 단어를 불러오는 함수를 작성했습니다.
- branch 명을 실수로 #97 이 아닌 #87로 작성했습니다.  죄송합니다. 참고해주세요!

[Feat] - todayword function

---

src/firebase/api/userAPI.js

- closes #110 
- 유저 정보를 삭제하는 함수를 구현했습니다.

[Feat] - #110 Add delete user

---

src/firebase/api/BadgeApi.js
src/firebase/root.js
src/firebase/type/typedef.js

- closes #116 
- 뱃지 취득일 속성을 추가했습니다.
- progressValue >= goalValue 일 경우 뱃지 취득일을 대입하도록 설정했습니다.
- 취득한 날짜가 있는 뱃지의 경우 유저가 로그인 할때 이벤트 리스너에 등록하지 않습니다

[Feat] - Add addedTime

---

src/firebase/api/BadgeApi.js
src/firebase/api/userAPI.js

- closes #117 
- 유저 정보 삭제가 제대로 작동하지 않는 문제를 수정했습니다.

[Fix] - Fix user delete

---

src/firebase/api/QuizApi.js
src/firebase/type/typedef.js

- closes #124 
- WordTestView date 속성 string -> Timestamp 변경
- WordTestView를 불러올때 date 값을 기준으로 오름차순으로 불러옵니다

[Fix] - WordTestView structure

---

src/firebase/api/userAPI.js

- closes #118 
- 새로운 유저의 정보를 초기화할때 myBadge 정보 추가를 제거했습니다.

[Fix] - Delete Initialize myBadge

---

src/Router.js
src/pages/mybadge/updateBadgeObject.js
src/pages/wordtestListPage/WordTestCell.jsx
src/pages/wordtestListPage/WordTestList.jsx
src/utils/ordinalSuffix.js

- closes #126
- WordTestList 정렬 문제로 데이터 구조 변경
- WordTestList 정렬 기능 추가 (별도로 프론트단에서 추가로 검증함.)
- #125 와 관련된 이슈입니다.

[Feat] change wordtestlist struction and sorting list

---

src/firebase/api/wordAPI.js

- closes #131 
-wordId를 통해 word 정보를 불러올때 발생하는 오류를 해결했습니다.
- comment를 불러오는 함수를 따로 분리하였고, query를 이용하여 하위 collection 정보를 불러옵니다.

[Fix] - #131 Fix get word data

---

src/components/Badge.jsx
src/components/BadgeNotification.jsx
src/components/BadgeNotificationGenerator.jsx
src/firebase/functions/Events.js
src/firebase/root.js
src/firebase/type/typedef.js
src/pages/wordtestSheetPage/WordTestSheet.jsx
src/styles/components/BadgeNotification.scss
src/types/const.js
src/utils/badgeImage.js

- closes #134
- 뱃지 조건 충족시 화면 띄우기!!!
- 사용하는 법. 뱃지 달성이 예상되는 페이지에 간다~
- 아래의 소스코드를 추가한다~
```jsx
const BadgeNotification = badgeNotificationGenerator(BADGE_TYPE_CONST);
...
<BadgeNotification />
```

[Feat] badge notification interaction

---

src/firebase/api/QuizApi.js
src/firebase/functions/Events.js

- closes #138
- 모의고사 뱃지 조건 변경 (score 5이상일 경우 이벤트 dispath)

[Feat] - #138 Update Test badge condition

---

src/firebase/root.js

[Fix] #111 - Fixed EventListener

---

src/pages/wordCommunityPage/Comment.jsx

- closes #142 
- reaction 버튼 오류 수정

[Fix] - #142 Fix comment reaction

---

README.md

- closes #145
- 7장의 키노트 이미지를 리드미 파일에 추가했습니다.

[Docs] #145 - Update README.md
